### PR TITLE
openssl_csr: add support for name constraints extension

### LINKED ISSUE #46: openssl_csr missing nameConstraints extension
##### SUMMARY

I was trying to limit domains an intermediate CA certificate can sign by adding a `nameConstraints`. However I couldn't find an option for that in `openssl_csr`. Is that implemented?
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssl_csr
##### ADDITIONAL INFORMATION

```yaml

```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #46.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
openssl_csr
openssl_csr_info

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
Ok, I had to add another commit. While adding this feature, I noticed that IP address ranges weren't supported at all so far. They cannot be used for SANs, but they *can* (and *must* - IP addresses won't work) be used for name constraints. I originally wanted to create a new PR for this, but noticed that I can only test it once this is merged - so I added it here :)

**Comment by felixfontein** [comment]
(rebased to remove conflict)

**Comment by MarkusTeufelberger** [comment]
Looks good to me.

Shipit! :-)

**Comment by felixfontein** [comment]
@MarkusTeufelberger thanks a lot for reviewing this!

**Pull request merged**
