### PR TITLE
Allow to run x509_certificate selfsigned provider without providing a CSR

### LINKED ISSUE #32: x509_certificate without csr_path
##### SUMMARY

An explicit `csr_path` shouldn't be required when generating an openssl certificate. A valid command to generate a certificate is `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`, which doesn't require a csr file.

https://github.com/ansible/ansible/issues/68736 was closed saying to post here. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssl_certificate

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The module will act as if a minimal CSR only containing the public key has been provided.

Fixes #32.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
x509_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by MarkusTeufelberger** [comment]
Hm, I'm still not sure if the resulting certificates are very useful, but I've already seen examples where certificates were just used to encode the public key for a key pair.

Anyways, the code looks good to me.

/shipit

**Comment by felixfontein** [comment]
I agree with that :)

**Comment by felixfontein** [comment]
@MarkusTeufelberger thanks for reviewing this!

**Pull request merged**
