### PR TITLE
x509_certificate: check existing certificate's signature for selfsigned and ownca provider

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
In stable-1 with the PyOpenSSL backend, this causes #406 to fail.

Can be replicated with the cryptography backend when `ownca_create_authority_key_identifier=false`. I will add tests for this later, that's why it's WIP now.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
x509_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
This fix exposed a bug in the tests: quite a few tests used a wrong CA private key that didn't fit to the CA certificate. I've added a check whether these two fit together, and fixed the tests in 356f9091bedb31ab928e6e7b8a99e33293e521dd.

**Comment by felixfontein** [comment]
ready_for_review

**Review by Ajpantuso — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@Ajpantuso thanks for reviewing this!

I will include a backport of this into #406, looks like I have to do it manually anyway.

**Pull request merged**
