### PR TITLE
AZP Coverage support for Ansible 2.9

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY

Pull in latest changes from shippable-migration-tool
ci_complete ci_coverage

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
The reported coverage changes seem bogus and can probably be ignored.

**Comment by felixfontein** [comment]
@gundalow thanks!

**Comment by MarkusTeufelberger** [comment]
Thanks, that report looks helpful to make sure a few missing edge cases are also getting tested.

**Comment by felixfontein** [comment]
@MarkusTeufelberger btw, that report was already available, if you go to https://codecov.io/gh/ansible-collections/community.crypto (you can also reach that by clicking the Coverage badge in the README), you can browse the folders to see which files have which coverage. If you log in with your GitHub account, you can also see the exact coverage for a file (for example https://codecov.io/gh/ansible-collections/community.crypto/src/main/plugins/modules/openssl_signature.py - it doesn't want to show it if not logged in for some reason).

**Pull request merged**
