### PR TITLE
Allow to pass CSR to acme_certificate as csr_content

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This allows to not write the CSR to disk, once openssl_csr (or another module) allows to generate it without disk access.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
acme_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Review by resmo — APPROVED** [review]
code LGTM
The `version_added` is missing in the docs, is this still a thing?

**Review by resmo — APPROVED** [review]

**Comment by felixfontein** [comment]
@resmo yes it is, I completely forgot (also in another PR) :) ansible/ansible#69291 should really get completed at some point...

BTW, I noticed I can improve `openssl_get_csr_identifiers` a bit by passing the CSR content in as stdin, instead of creating a temp file on disk.

**Comment by resmo** [comment]
> @resmo yes it is, I completely forgot (also in another PR) :) [ansible/ansible#69291](https://github.com/ansible/ansible/pull/69291) should really get completed at some point...
> 
> BTW, I noticed I can improve `openssl_get_csr_identifiers` a bit by passing the CSR content in as stdin, instead of creating a temp file on disk.

Got that, really nice.

**Comment by felixfontein** [comment]
@resmo thanks a lot for reviewing this! I'll merge once CI passes (which will be in ~2 hours, since it's now clogged with the "nightly" builds...).

**Pull request merged**
