### PR TITLE
[stable-1] x509_certificate: regenerate certificate on CA's subject change

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #402 to stable-1.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
x509_cerificate

### CODE REVIEW

**Comment by felixfontein** [comment]
Hmm, looks like the fix in #402 was not complete: public key changes are only detected due to authority key identifier no longer matching. Without that extension, the module doesn't notice anything - which is obvious for the PyOpenSSL backend which does not support authority key identifier.

**Comment by felixfontein** [comment]
TODO: implement checks in https://github.com/ansible-collections/community.crypto/pull/407 for PyOpenSSL backends

**Comment by felixfontein** [comment]
It looks like this cannot be done with PyOpenSSL :-(

**Comment by felixfontein** [comment]
Finally, this is ready for review :)

**Comment by felixfontein** [comment]
@Ajpantuso if you have a bit of time, it would be great if you could take a look at this! :)

**Review by Ajpantuso — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@Ajpantuso thanks a lot for reviewing this!

**Pull request merged**
