### PR TITLE
Refactor module_utils/crypto.py

### LINKED ISSUE #16: TODO: Refactor module_utils/crypto.py
Make it a subdirectory and split that file up into several smaller files.

This allows modules to include only the parts they actually need.

Requires ~~#7 and~~ #9 to be merged first.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Expands the large monolithic `plugins/module_utils/crypto.py` into a Python package `plugins/module_utils/crypto/` with multiple smaller files.

This should not change functionality at all (except fix a tiny bug in x509_crl.py I found while changing this). CI should check essentially everything, except `ecs_certificate` (and the ECS part of `x509_certificate`) - @ctrufan can you test it?

I've used pylint and flake8 to check for errors (and clean up unnecessary imports), so the change should be pretty safe.

Fixes #16.

CC @MarkusTeufelberger @puiterwijk @Spredzy @Shaps @ctrufan

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
plugins/module_utils/crypto.py

### CODE REVIEW

**Comment by felixfontein** [comment]
(Unstable CI is caused by #23 and unrelated to this PR.)

**Comment by felixfontein** [comment]
I moved some generic file I/O methods (`load_file_if_exists` and `write_file`) into a new Python module `plugins/module_utils/io.py`. This makes them easier to use without also having to include the pyOpenSSL / cryptography feature detection.

I also added a new support function for obtaining the serial number of a `cryptography` certificate, since that changed in cryptography 1.4. Instead of repeating the same `try/except` in different modules, there's now one common utility function for that.

**Comment by felixfontein** [comment]
I've added some compatibility code to `module_utils/crypto/__init__.py`. With this, even existing modules and existing code depending on `module_utils/crypto.py` should work without change - well, should, assuming ansible/ansible#68872 wouldn't be there. But once that's fixed, it will work :)

**Comment by felixfontein** [comment]
(The current error in macOS is caused by pyca/cryptography#5215)

**Comment by felixfontein** [comment]
@MarkusTeufelberger @puiterwijk @Spredzy @Shaps @ctrufan I would be really happy if you could review this PR :)

**Comment by ctrufan** [comment]
Apologies, I've been super busy - I should have a chance to retest the ecs_certificate module some time this week. I'll see if I can find time this weekend to review the PR as well.

**Comment by felixfontein** [comment]
The problem with cryptography on old macOS versions has been resolved with the release of cryptography 2.9.2. Now it's back to "unstable" as before.

**Comment by MarkusTeufelberger** [comment]
Looks good to me, let's move this forward. Thanks for the work, Felix!

**Comment by felixfontein** [comment]
I'll merge this now, so work can continue ;) @MarkusTeufelberger thanks for checking this! @ctrufan the change should be pretty safe for the ecs_* modules, but it probably won't hurt when you test it at some point. You should definitely test it before we release 1.0.0 of the collection anyway ;)

**Pull request merged**
