### PR TITLE
Run tests with macOS 10.15.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Also run tests against macOS 10.15 in CI.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
The failure is potentially caused by macOS 10.15 coming with an older LibreSSL version (LibreSSL 2.8.3, released on 2018-12-15). cryptography ships its own libssl (OpenSSL 1.1.1g  21 Apr 2020). The error in question is probably caused by libressl-portable/portable#472 which was only fixed after that release was made.

**Comment by felixfontein** [comment]
ready_for_review

**Review by Andersson007 — APPROVED** [review]
the test expansion looks good to me, thanks!
shipit

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing!

**Pull request merged**
