### PR TITLE
Improve PEM identification

### LINKED ISSUE #627: x509_certificate_info detects a PEM certificate as a DER certificate
##### SUMMARY
`x509_certificate_info` interpretes a valid PEM certificate file as a DER certificate file.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```paste below
2.12.2
2.13.1
2.14.1
```

##### COLLECTION VERSION

```paste below
2.14.0
```

See #603

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: "check cert"
   x509_certificate_info:
     path: "{{ certificate_x509_certificate_path }}"
```

and the certificate-file looks like:

```
subject=CN=example.com, OU=Unit, O=Organization, L=Location, S=State, C=DE
issuer=CN=RSA-SubCA1, OU=PKI, O=Organization, L=Location, S=State, C=DE
-----BEGIN CERTIFICATE-----
BASE64-Certificate
-----END CERTIFICATE-----
subject=CN=RSA-SubCA1, OU=PKI, O=Organization, L=Location, S=State, C=DE
issuer=CN=RSA-RootCA, OU=PKI, O=Organization, L=Location, S=State, C=DE
-----BEGIN CERTIFICATE-----
BASE64-Sub-CA
-----END CERTIFICATE-----
subject=CN=RSA-RootCA, OU=PKI, O=Organization, L=Location, S=State, C=DE
issuer=CN=RSA-RootCA, OU=PKI, O=Organization, L=Location, S=State, C=DE
-----BEGIN CERTIFICATE-----
BASE64-ROOT-CA
-----END CERTIFICATE-----

```

##### ACTUAL RESULTS

```paste below
fatal: [example.com]: FAILED! => changed=false 
  msg: 'Cannot parse DER certificate: Unable to load certificate'
```

##### PROBLEM
https://github.com/ansible-collections/community.crypto/blob/main/plugins/module_utils/crypto/pem.py#L21

```python
        if lines[0].startswith(PEM_START) and lines[0].endswith(PEM_END) and len(lines[0]) > len(PEM_START) + len(PEM_END):
```` 

you check, if the PEM-Begin is in the first row. According to specification [rfc7468](https://www.rfc-editor.org/rfc/rfc7468), there may be anything before the BEGIN and the parser MUST NOT abort.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #627.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/crypto/pem.py

### CODE REVIEW

**Comment by felixfontein** [comment]
@MarkusTeufelberger @Ajpantuso if you have time to review this, a review would be appreciated :)

**Review by Ajpantuso — APPROVED** [review]
LGTM

**Comment by MarkusTeufelberger** [comment]
Seems weird that `cryptography` does not really have code for this. :-/

The "extract_first_pem()" code seems to be in https://docs.rs/pem/latest/pem/ and maybe also a little bit exposed in https://github.com/pyca/cryptography/blob/35219339d937b35435813d0995b5573a1d665cf2/src/rust/src/x509/common.rs#L16, but I'm not sure if that's much better than just rolling our own for now.

LGTM

**Comment by felixfontein** [comment]
@MarkusTeufelberger it would be nice if it would expose that... Unfortunately even if they changed that now, it would take years until we could fully rely on it and stop having our own code for it :)

**Comment by felixfontein** [comment]
@Ajpantuso @MarkusTeufelberger thanks a lot for reviewing this!

**Pull request merged**
