### PR TITLE
Remove dependency on ansible.netcommon collection

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Right now the community.crypto collection has a dependency on [ansible.netcommon](https://github.com/ansible-collections/netcommon/) only because of [module_utils/compat/ipaddress.py](https://github.com/ansible-collections/netcommon/blob/master/plugins/module_utils/compat/ipaddress.py).

While I generally don't like duplicating code, I don't see why we should have a network device collection as a dependency only for one file which only "randomly" ended up in that collection (it's a vendored version of https://pypi.org/project/ipaddress/).

CC @ctrufan @MarkusTeufelberger @puiterwijk @Shaps @Spredzy @Xyon

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/compat/ipaddress.py

### CODE REVIEW

**Comment by felixfontein** [comment]
Tested with:
 * `ansible-test integration -v --truncate=0 --docker-no-pull --docker ubuntu1804`
 * `ansible-test units --python 3.7 --docker default --color -v`
 * `ansible-test sanity -v --truncate=0 --docker-no-pull --docker`

**Comment by gundalow** [comment]
Should we add a note in the file in `ansible.netcommon` to say we've forked it? That might help protect us if someone makes an updated to the original version?

**Comment by MarkusTeufelberger** [comment]
Isn't the "original version" actually https://pypi.org/project/ipaddress/ anyways?

**Comment by gundalow** [comment]
> Isn't the "original version" actually https://pypi.org/project/ipaddress/ anyways?

Yup, though in ansible.netcommon would help a bit. 
Either way, if the maintainers of `community.crypto` are happy then I'm +1 to this PR

**Comment by MarkusTeufelberger** [comment]
"Friendship ended with `ansible.netcommon` - Now upstream is our best friend!" :-P

In all seriousness though a note might help the `netcommon` team to track if they even need to keep these vendored files around.

**Comment by felixfontein** [comment]
There are other modules in community.general which use ipaddress from ansible.netcommon.

**Pull request merged**
