### PR TITLE
Use FQCN in examples

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Changes all examples to use FQCN (fully qualified collection names) instead of short names.

Mainly to make sure that people copying from the examples will end up with something that is future-proof. (I'm not aware of any plans to disable routing. But eventually we add new modules which won't have a valid shortname, and suddenly you need to use the FQCN for some modules, while you can't use it for others. So let's teach new users to use FQCNs directly :) )

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
all

### CODE REVIEW

**Comment by resmo** [comment]
I read somewhere that examples should not be adjusted to use the FQCN. @gundalow any comment on that?

**Comment by felixfontein** [comment]
@resmo I've seen this question pop up before, but I've never seen a real answer to it. Would be really good to know, since I guess a lot of people will have the same question :)

**Comment by gundalow** [comment]
Thanks for the ping, this made me realise that we haven't documented this yet. 

Based on discussion just now in  `#ansible-community`, I've created https://github.com/ansible-collections/overview/issues/40

**Comment by Shaps** [comment]
LGTM

**Comment by felixfontein** [comment]
@resmo @gundalow @Shaps thanks! :)

**Pull request merged**
