### PR TITLE
Add version_added for all new features

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds `version_added: '1.0.0'` to all new features (since Ansible 2.9). I'll stick to `1.0.0` until we decided how we'll version and what's the next release.

(Similar to ansible-collections/community.general#214)

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
multiple

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
In some places you wrote `2.10`, is that on purpose?

**Comment by felixfontein** [comment]
@MarkusTeufelberger it's not on purpose. I'll update all values to the correct one once we have decided which one will be the initial "proper" release. (The 0.1.0 currently on galaxy is kind of a bootstrap release - mainly needed because you cannot upload collections to galaxy with dependencies when these are not on galaxy yet.)

**Comment by felixfontein** [comment]
It now says 1.0.0 everywhere.

**Comment by MarkusTeufelberger** [comment]
lgtm

**Comment by felixfontein** [comment]
@MarkusTeufelberger thanks for reviewing this!

**Pull request merged**
