### PR TITLE
CI tests: add a note not to use tests as an example of writing roles

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
CI tests: add a note not to use tests as an example of writing roles because the tests are included in release tarballs

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
CI tests

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
The better fix would be to not ship tests in releases...

I guess it is fine to make the releases even larger in this case until this is fixed upstream. ;-)

**Comment by Andersson007** [comment]
@MarkusTeufelberger maybe:) This was discussed at community meeting though:)

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@MarkusTeufelberger it was discussed here: https://meetbot.fedoraproject.org/ansible-community/2020-09-23/ansible_community_meeting.2020-09-23-18.01.log.html The main reason keep including tests are a) potential GPL compliance problems, and b) enabling packagers to run tests themselves.

**Comment by Andersson007** [comment]
@felixfontein @MarkusTeufelberger thanks for reviewing!

**Pull request merged**
